### ISSUE TITLE
Under Gnome shell, no Close or maximise buttons are displayed

### ISSUE THREAD

**Issue by jmaris** [Zonnev/elementaryos-firefox-theme#51] opened 2019-12-06 14:08 UTC
Hi,

I've been trying to use this theme under gnome shell, with the Adamentary GTK theme, however I cannot get it to display a close button :( any idea ?

**Comment by Zonnev** [comment] 2019-12-06 15:41
This theme has the window buttons from elemenary OS GTK standard. I did not theme these buttons so in another GTK theme (run in elementary OS) the buttons should theme with it. 

All I can say is that this theme is made exclusively for elementary OS and its native GTK.

**Comment by Chamrosh** [comment] 2019-12-11 22:34
![Screenshot from 2019-12-12 02 01 59](https://user-images.githubusercontent.com/10561726/70666275-92f45100-1c83-11ea-8398-7d755721d899.png)

**Comment by LynuxDevz** [comment] 2019-12-11 22:49
Can confirm it does happen to me as well using elementary's stock GTK (dark) theme.

A change in FF71 css seems to be the cause of this issue, I made some tests using a previous version of the css file, resetting a profile to default, and even changing the firefox version from AppCenter to the official Linux binary. None of that helped displaying the buttons again.

**Comment by Zonnev** [comment] 2019-12-12 10:41
@Chamrosh In elementary Tweaks your Window Controls > Layout is not set on elementary. That why you don't see the window buttons in Firefox. This theme only displays the standard elementary window buttons. Hope this helps for all of you.

**Comment by andreacocci95** [comment] 2020-02-29 10:47
I have the same problem. I know that if I set elementary style for buttons it works, but I want to use my custom position of buttons (close only right) and I want also use this theme that make firefox integrated with elementary style. Can somebody fix this problem?

**Comment by Zonnev** [comment] 2020-04-20 10:55
The theme now supports all button layouts from Tweaks. So I close this issue.

**Closed by Zonnev** 2020-04-20 10:55 UTC
